spring.application.name=product-service

spring.datasource.url=jdbc:postgresql://${DBHOST:localhost}:${DBPORT:5432}/${DBNAME:productdb}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${DBUSER:product}
spring.datasource.password=${DBPASSWORD:product}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

tax.rate=0.19

logging.structured.format.console=ecs
