apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
  namespace: lite
spec:
  replicas: 5
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
        - name: product
          image: mauron/product:7
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: product-config
            - secretRef:
                name: product-secret
